baseURL = "https://blog.cetico.org/"
languageCode = "en-us"
title = "blog.cetico.org"
theme="rocinante"
copyright = "© Yves Junqueira"
# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nictuku"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/cetico/"
[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/yvesjunqueira/"


[services]
  [services.googleAnalytics]
    ID = 'G-YHFCQF5CLD'
