baseURL = "https://blog.cetico.org/"
languageCode = "en-us"
title = "blog.cetico.org"
theme="rocinante"
copyright = "© Yves Junqueira"
# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nictuku"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/cetico/"
[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/yvesjunqueira/"

[params]
  about = """
Yves Junqueira é um engenheiro de software. Ele é um dos fundadores da Artell, uma empresa de consultoria em tecnologia. Yves é um entusiasta de software livre e de código aberto. Ele também foi um dos fundadores da YourBase, uma empresa que criava ferramentas para desenvolvimento de software. Yves foi um engenheiro sênior na Google, onde trabalhou em projetos de infraestrutura e produtos de mensangeria.
"""

[services]
  [services.googleAnalytics]
    ID = 'G-YHFCQF5CLD'
